FROM maven:3-openjdk-11 AS mvn
RUN git clone https://github.com/spring-projects/spring-petclinic.git
RUN cd spring-petclinic && mvn package

FROM openjdk:11
LABEL author="vasu"
COPY /spring-petclinic/target/spring-petclinic-2.4.5.jar /spring-petclinic-2.4.5.jar
EXPOSE 8080
CMD ["java", "-jar", "/spring-petclinic-2.4.5.jar"]