---
apiVersion: v1
kind: Pod
metadata: 
  name: other-pod
spec:
  containers:
    - name: httpd
      image: httpd
      ports: 
        - containerPort: 80
    - name: mysql
      image: mysql
      ports:
        - containerPort: 3306
      env: 
        - name: MYSQL_ROOT_PASSWORD
          value: 'vasu@123'