---
- name: install utility softwares
  import_playbook: "{{ filename1 }}.yaml"
  vars:
    utility_softwares:
      - git
      - wget
      - tree
- name: create files
  include: "{{ filename2 }}.yaml"
  vars:
    file_list:
      - /tmp/1.txt
      - /tmp/2.txt