---
- name: Installation of Tomcat9
  hosts: all
  become: yes
  Tasks:
    - name: Install Java Package
      apt:
        name: "{{ java_package }}"
        update_cache: yes
        state: present
    - name: Ensure the Groupname Exists
      group:
        name: "{{ tomcat_groupname }}"
        state: present
    - name: Make sure the Tomcat Home directory exists
      file:
        path: "{{ tomcat_home_dir }}"
        state: directory
    - name: Add Tomcat user to group within tomcat home directory
      user:
        name: "{{ tomcat_username }}"
        group: "{{ tomcat_groupname }}"
        home: "{{ tomcat_home_dir }}"
        shell: "{{ tomcat_Shell }}"
    - name: Download the tomcat
      get_url:
        url: "{{ tomcat_download_url }}"
        dest: "{{ tomcat_download_dest }}"
    - name: Extract the tomcat
      unarchive:
        src: "{{ tomcat_download_dest }}"
        dest: "{{ tomcat_home_dir }}"