---
- name: Installation of Tomcat9
  hosts: all
  become: yes
  tasks:
    - name: Install Java Package
      apt:
        name: "{{ java_package }}"
        update_cache: yes
        state: present
    - name: Ensure the Groupname Exists
      group:
        name: "{{ tomcat_groupname }}"
        state: present
    - name: Make sure the Tomcat Home directory exists
      file:
        path: "{{ tomcat_home_dir }}"
        state: directory
    - name: Add Tomcat user to group within tomcat home directory
      user:
        name: "{{ tomcat_username }}"
        group: "{{ tomcat_groupname }}"
        home: "{{ tomcat_home_dir }}"
        shell: "{{ tomcat_shell }}"
    - name: Download the tomcat
      get_url:
        url: "{{ tomcat_download_url }}"
        dest: "{{ tomcat_download_dest }}"
    - name: Check if the tomcat is extracted
      stat:
        path: "{{ tomcat_check_dir }}"
      register: tomcat_conf
    - name: untar the tomcat
      command: "tar xzvf {{ tomcat_download_dest }} -C {{ tomcat_home_dir }} --strip-components=1"
      when: not tomcat_conf.stat.exists