---
apiVersion: v1
kind: Pod
metadata:  
  name: label_demo1
  labels:
    environment: developer
    team: infra-ops
    projetc: qt-commerce
spec: 
  containers: 
    - name: nginx-container
      image: nginx
      ports: 
        - containerPort: 80
          protocol: TCP
