---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy 
  labels: 
    app: frontend
spec: 
  replicas: 3
  minReadySeconds: 20
  selector:
    matchLabels:
      app: frontend
      environment: production
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template: 
    metadata:
      labels:
        app: frontend
        environment: production
        version: "2.60"
    spec:
      containers:
        - name: frontend-container
          image: ngnix
          ports:
            - containerPort: 80
              protocol: TCP
        
